name: SonarQube Analysis

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    container:
      image: sonarsource/sonar-scanner-cli:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=http://homelab-sonarqube:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectKey=wt-sim-project \
            -Dsonar.projectName="WT Sim Project" \
            -Dsonar.sources=.

  # ---------------------------------------------------------------------------
  # LLM Code Review (on PRs only) - posts comment directly on PR
  # ---------------------------------------------------------------------------
  ai-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR diff
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff origin/${{ github.base_ref }}...HEAD > /tmp/pr.diff
          echo "Diff size: $(wc -c < /tmp/pr.diff) bytes"
          echo "First 500 chars of diff:"
          head -c 500 /tmp/pr.diff

      - name: AI Code Review
        env:
          FORGEJO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          python3 << 'EOF'
          import json, urllib.request, os

          with open('/tmp/pr.diff', 'r', errors='replace') as f:
              diff = f.read()

          print(f"Diff size: {len(diff)} bytes")

          if len(diff) > 50000:
              review = f"Diff too large for AI review ({len(diff)} bytes). Please review manually."
          else:
              diff = diff[:30000]
              print("Calling Ollama...")

              prompt = f"""You are a code reviewer. Review this git diff and provide feedback on:
          1. Potential bugs or errors
          2. Security issues
          3. Suggested improvements

          Be concise. Only mention real issues, not style preferences.

          ```diff
          {diff}
          ```

          Provide your review in plain text (not JSON):"""

              payload = json.dumps({
                  "model": "qwen2.5-coder:7b",
                  "prompt": prompt,
                  "stream": False,
                  "options": {"temperature": 0.1, "num_predict": 1024}
              }).encode()

              try:
                  req = urllib.request.Request(
                      "http://host.docker.internal:11434/api/generate",
                      data=payload,
                      headers={"Content-Type": "application/json"}
                  )
                  with urllib.request.urlopen(req, timeout=180) as resp:
                      result = json.load(resp)
                      review = result.get("response", "No response from model")
                      print(f"Got review: {len(review)} chars")
                      print(f"Preview: {review[:200]}")
              except Exception as e:
                  review = f"Error calling Ollama: {e}"
                  print(review)

          comment_body = f"## 🤖 AI Code Review\n\n{review}"
          payload = json.dumps({"body": comment_body}).encode()

          req = urllib.request.Request(
              f"http://forgejo:3000/api/v1/repos/{os.environ['REPO']}/issues/{os.environ['PR_NUMBER']}/comments",
              data=payload,
              headers={"Content-Type": "application/json", "Authorization": f"token {os.environ['FORGEJO_TOKEN']}"}
          )

          try:
              with urllib.request.urlopen(req, timeout=30) as resp:
                  print(f"Comment posted to PR #{os.environ['PR_NUMBER']}")
          except Exception as e:
              print(f"Failed to post comment: {e}")
          EOF
