/**
 * AIGeneratedBadge - Green accent indicator for AI-generated content
 * Displays generation timestamp on hover
 */

interface AIGeneratedBadgeProps {
  /** ISO timestamp of when the content was generated */
  generatedAt: string;
}

export function AIGeneratedBadge({ generatedAt }: AIGeneratedBadgeProps) {
  return (
    <span
      className="inline-flex items-center gap-1.5 px-2 py-0.5 text-[10px] font-mono uppercase tracking-widest text-green-400 bg-green-500/10 border border-green-500/30 rounded"
      title={`Generated ${generatedAt}`}
      aria-label="Content generated by AI"
    >
      <span className="w-1.5 h-1.5 rounded-full bg-green-400" aria-hidden="true" />
      AI Generated
    </span>
  );
}
